<a href="https://colab.research.google.com/github/dhirendra123/boostraplearning/blob/master/deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf 

In [2]:
tf.__version__

'2.2.0'

In [3]:
hello =tf.constant("hello") # creating a constant 
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [4]:
world=tf.constant("world") 
world

<tf.Tensor: shape=(), dtype=string, numpy=b'world'>

In [5]:
type(hello) #checking its type 

tensorflow.python.framework.ops.EagerTensor

In [6]:
with tf.compat.v1.Session() as sess:

  a = tf.constant(5.0)
  b = tf.constant(6.0)
  c = tf.multiply(a, b)

  result = sess.run(c)
  print(result)

30.0


In [7]:
with tf.compat.v1.Session() as sess:
  r=tf.constant("hello")
  c=sess.run(r)
  print(c)

b'hello'


In [19]:
with tf.compat.v1.Session() as sees:
  ma_1=tf.zeros((5,5))
  m2=sees.run(ma_1)
  print(m2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
with tf.compat.v1.Session() as sees:
  mat_1=tf.fill((5,5),10)
  m3=tf.random.normal((5,5))
  m2=sees.run(mat_1)
  m5=sees.run(m3)
  print(m2)
  print ('\n')
  print(m5)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[-2.4408092  -0.7402636  -0.8390685   0.28572863 -0.11664183]
 [-1.1892618   0.098507   -0.74252486  0.47722095  2.8380084 ]
 [ 1.0259771   2.8955739   0.97385603 -1.9901167   0.20364812]
 [ 0.500339   -1.6789699  -0.29832155 -0.693038    0.46616098]
 [-1.5910883  -2.5396018   1.0188396   0.51363105  1.7086931 ]]
